### ISSUE TITLE
Row types are unsupported

### ISSUE THREAD

**Issue by chris-is** [JetBrains/kotlin-spark-api#73]
Hello, I'm trying out preview1 by refactoring some ETL code, and I get the following error when attempting to join two Dataframes (Dataset of type Row):

`Exception in thread "main" java.lang.IllegalArgumentException: org.apache.spark.sql.Row is unsupported
	at org.jetbrains.kotlinx.spark.api.ApiV1Kt.schema(ApiV1.kt:307)
	at org.jetbrains.kotlinx.spark.api.ApiV1Kt.schema(ApiV1.kt:301)
	at org.jetbrains.kotlinx.spark.api.ApiV1Kt.schema$default(ApiV1.kt:261)
	at org.jetbrains.kotlinx.spark.api.ApiV1Kt$memoizedSchema$1.invoke(ApiV1.kt:346)
	at org.jetbrains.kotlinx.spark.api.ApiV1Kt$memoizedSchema$1.invoke(ApiV1.kt)
	at org.jetbrains.kotlinx.spark.api.Memoize1.invoke(ApiV1.kt:341)
	at org.jetbrains.kotlinx.spark.api.ApiV1Kt.generateEncoder(ApiV1.kt:95)`

In the earlier stages of my transformations, I don't need type safety and performance is of the essence, so I use `Row` types, but it doesn't seem to be supported here. 

Thank you in advance for looking into this! This is a great initiative and has a lot of value for someone like me who writes ETL pipelines in Kotlin w/ Spark.

**Comment by asm0dey** [comment]
Hello! Sorry for not answering for a long time, it looks like I somehow don't receive notification from github O_O

Could you please post an example code to reproduce? Do I understand correctly that you're joining to raw dataframes?
If so — I believe you should use Spark's join, not left/right/inner join and not joinWith

**Comment by asm0dey** [comment]
Closing it as stale for now. Feel free to reopen.
