### ISSUE TITLE
`kotlin.jvm.internal.Reflection.typeOf(Ljava/lang/Class;)Lkotlin/reflect/KType;` not found

### ISSUE THREAD

**Issue by piiertho** [JetBrains/kotlin-spark-api#90]
Hello !
I tried to run a spark job following [this tutorial](https://github.com/JetBrains/kotlin-spark-api/wiki/Quick-Start-Guide).
Then I build a shadow jar, send it to `HDFS`, and ask livy to start my job.
When application starts, it says `typeOf` method is not found:
```
21/06/01 16:06:00 INFO ContextHandler: Started o.s.j.s.ServletContextHandler@55d10431{/SQL,null,AVAILABLE,@Spark}
21/06/01 16:06:00 INFO ServerInfo: Adding filter to /SQL/json: org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter
21/06/01 16:06:00 INFO ContextHandler: Started o.s.j.s.ServletContextHandler@5bf00ac7{/SQL/json,null,AVAILABLE,@Spark}
21/06/01 16:06:00 INFO ServerInfo: Adding filter to /SQL/execution: org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter
21/06/01 16:06:00 INFO ContextHandler: Started o.s.j.s.ServletContextHandler@33998172{/SQL/execution,null,AVAILABLE,@Spark}
21/06/01 16:06:00 INFO ServerInfo: Adding filter to /SQL/execution/json: org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter
21/06/01 16:06:00 INFO ContextHandler: Started o.s.j.s.ServletContextHandler@126cc16d{/SQL/execution/json,null,AVAILABLE,@Spark}
21/06/01 16:06:00 INFO ServerInfo: Adding filter to /static/sql: org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter
21/06/01 16:06:00 INFO ContextHandler: Started o.s.j.s.ServletContextHandler@75595dc6{/static/sql,null,AVAILABLE,@Spark}
21/06/01 16:06:02 ERROR ApplicationMaster: User class threw exception: java.lang.NoSuchMethodError: kotlin.jvm.internal.Reflection.typeOf(Ljava/lang/Class;)Lkotlin/reflect/KType;
java.lang.NoSuchMethodError: kotlin.jvm.internal.Reflection.typeOf(Ljava/lang/Class;)Lkotlin/reflect/KType;
    at org.mycompany.spark.sandbox.ApplicationKt.main(Application.kt:54)
    at org.mycompany.spark.sandbox.ApplicationKt.main(Application.kt)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:728)
21/06/01 16:06:02 ERROR ApplicationMaster: Uncaught exception:
org.apache.spark.SparkException: Exception thrown in awaitResult:
    at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:302)
    at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:500)
    at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:264)
    at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:892)
    at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:891)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:422)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
    at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:891)
    at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)
Caused by: java.util.concurrent.ExecutionException: Boxed Error
    at scala.concurrent.impl.Promise$.resolver(Promise.scala:87)
    at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:79)
    at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
    at scala.concurrent.Promise.tryFailure(Promise.scala:112)
    at scala.concurrent.Promise.tryFailure$(Promise.scala:112)
    at scala.concurrent.impl.Promise$DefaultPromise.tryFailure(Promise.scala:187)
    at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:747)
Caused by: java.lang.NoSuchMethodError: kotlin.jvm.internal.Reflection.typeOf(Ljava/lang/Class;)Lkotlin/reflect/KType;
    at org.mycompany.spark.sandbox.ApplicationKt.main(Application.kt:54)
    at org.mycompany.spark.sandbox.ApplicationKt.main(Application.kt)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:728)
```

It seems it cannot find kotlin stdlib classes.

Here is gradle build script:
```kotlin
import java.net.URI
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    java
    kotlin("jvm") version "1.4.31"

    id("com.github.johnrengelman.shadow") version "6.1.0"
}

group = "org.mycompany.spark"
version = "1.0-SNAPSHOT"

val compileKotlin: KotlinCompile by tasks

compileKotlin.kotlinOptions.jvmTarget = "1.8"

dependencies {
    implementation(kotlin("stdlib"))
    implementation("org.jetbrains.kotlinx.spark:kotlin-spark-api-3.0.0_2.12:1.0.0-preview1")
    compileOnly("org.apache.spark:spark-sql_2.12:3.0.0")
}

tasks.withType<ShadowJar> {
    manifest {
        attributes["Main-Class"] = "org.mycompany.spark.sandbox.ApplicationKt"
    }
    dependencies {
        exclude { it.moduleGroup == "org.apache.spark" || it.moduleGroup == "org.scala-lang" }
    }
}
```

And the dummy spark job I try to run:
```kotlin
package org.mycompany.spark.sandbox

import org.jetbrains.kotlinx.spark.api.withCached
import org.jetbrains.kotlinx.spark.api.withSpark

fun main() {
    withSpark {
        dsOf(0, 1, 2, 4, 5, 6).withCached {
            println("File contains ${count()} lines")
        }
    }
}
```

Also I tried to add `kotlin-reflect` dependency, but this does not change anything.

EDIT : Here is minimal reproduction project : https://github.com/piiertho/minimal-reproduction-kt-spark

**Comment by Jolanrensen** [comment]
This sounds like something that a Kotlin version bump might solve on our side. The planning is to release an updated version of the API when Kotlin 1.5.20 is released. In the meantime you might be able to install the main branch into your maven local to use it in your project (that's how I'm currently using the API).

**Comment by piiertho** [comment]
Hello ! 
Thank you for your support !
I'm trying right now to compile from master and install to my local maven.
I'm encountering issues when running API for Spark 2.4+ tests.
It cannot find some spark classes :
```
[ERROR] Errors:
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.analysis.FunctionRegistry$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.analysis.FunctionRegistry$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.analysis.FunctionRegistry$
[ERROR]   null
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
[ERROR]   Could not initialize class org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator$
```
I don't see any specific configuration in you CI workflow :/
Do you have any idea ?

**Comment by asm0dey** [comment]
@piiertho please try again. Now it compiles and contains the latest version of Kotlin.

**Comment by asm0dey** [comment]
Closing it as stale for now, feel free to reopen
