### ISSUE TITLE
`ApiV1Kt.generateEncoder` method is not support enum class

### ISSUE THREAD

**Issue by nonpool** [JetBrains/kotlin-spark-api#98]
code:
```kotlin
fun main() {
    withSpark(appName = "Simple Application") {
        dsOf(1,2).map { A(E.E1) }.show(false)
    }
}

data class A(
    val e: E
)

enum class E {
    E1, E2
}
```

result: 
```
Exception in thread "main" java.lang.IllegalArgumentException: com.******.job.E is unsupported
	at org.jetbrains.kotlinx.spark.api.ApiV1Kt.schema(ApiV1.kt:923)
	at org.jetbrains.kotlinx.spark.api.ApiV1Kt.schema(ApiV1.kt:900)
	at org.jetbrains.kotlinx.spark.api.ApiV1Kt.schema$default(ApiV1.kt:842)
	at org.jetbrains.kotlinx.spark.api.ApiV1Kt$memoizedSchema$1.invoke(ApiV1.kt:964)
	at org.jetbrains.kotlinx.spark.api.ApiV1Kt$memoizedSchema$1.invoke(ApiV1.kt:964)
	at org.jetbrains.kotlinx.spark.api.Memoize1.invoke(ApiV1.kt:959)
	at org.jetbrains.kotlinx.spark.api.ApiV1Kt.generateEncoder(ApiV1.kt:167)
	at com.ikea.aid.recomm.pax.job.SparkApp.kotlinRun(SparkApp.kt:85)
	at com.ikea.aid.recomm.pax.job.SparkAppKt.main(SparkApp.kt:13)
	at com.ikea.aid.recomm.pax.job.SparkAppKt.main(SparkApp.kt)

```

other info:
```
    implementation 'org.jetbrains.kotlinx.spark:kotlin-spark-api-3.0:1.0.1'
    implementation 'org.apache.spark:spark-sql_2.12:3.1.1'
    implementation 'org.codehaus.janino:janino:3.0.16'
 
   kotlin version: 1.5.0

  openjdk version "11.0.10" 2021-01-19
  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
  OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

```

**Comment by nonpool** [comment]
@asm0dey

**Comment by asm0dey** [comment]
Wow, thank you, I'll look into this today
